name: Before merge to 'termit'

on:
  push:
    branches: [ termit ]
  pull_request:
    branches: [ termit ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x :lemmatizer-morphodita:build -x :lemmatizer-tests:build
